### ISSUE TITLE
[Feature Request]: Solution for database cause lag

### ISSUE THREAD

**Issue by EncryptSL** [EncryptSL/LiteEco#66]
### Type of function to add or improvement

API, Others

### TODO

- [x] Add AccountAPI interface
- [x] Add PlayerAccount class, and logic stuff for saving data from database into HashMap Cache.
- [x] Add account data from database during login into AccountCache.
- [x] Add async saving to database during player quit game or stop/crash server.
- [x] Needs testing functions, before release 1.4.0 version.

### Changelog: 1.4.0
- LiteEcoEconomyAPI was adapted to caching and hybriding mode by default.
- Added AccountAPI interface for PlayerAccount Manager.
- Added PlayerAccount stuff for caching.
- Fixed database cause lag
- LcyDev Merged his huge update & improvements, thanks for help 👍 🏆 . 
- Refactored object name Money to Account for better clarity and consistency.
- Refactored the PlaceHolderExtensionProvider for enhanced functionality.
- General refactoring to eliminate repeated code and merge translation-related code.
- Improved readability by refactoring player name filtering.
- Refactored the PlaceholderExtensionProvider for better performance.
- Further refactorings in the main class for better organization.
- Removed unused extensions for a cleaner codebase.
- Added an initializer for MiniMessage.
- Implemented purgeInvalidAccounts() to clean up invalid account data.
- Refactored PreparedStatements for better database interactions.
- Refactored MigrationTool for smoother data migration.
- Additional small changes and improvements.
- Config was changed
- Now you can change formatting format yourself.
- Language files was changed.

Related to #65
