### ISSUE TITLE
[Feature Request]: LiteEco version 2.0.0 | MultiCurrency update

### ISSUE THREAD

**Issue by EncryptSL** [EncryptSL/LiteEco#84]
### Type of function to add or improvement

API, Others

### Your ideas

**Todo Map:**

- [x] Change LiteEconomyAPI, on multi currency supporting.
- [x] Change saving of balance cache because now cache supports only one currency.
- [x] Change table, from object to Class Table need accept settings from config.yml. For custom currency.
- [x] Primary will be set vault like a primary currency.
- [x] Change on multi currencies except change in command segment, for accept other currencies.

**Knowned Bugs:**
- [x] Updating of config.yml while is updated not working.
- [x] Updating of localization is same bug with config.yml.

Other sutff will be added later.
